baseURL = 'https://skpuindo.com/'
locale = 'en-us'
title = 'S.K. Puindo, epic fantasy author'
copyright = "© S.K. Puindo"
theme = "hugo-neso"

enableRobotsTXT                = true

mainSections                   = ["posts", "books"]
pluralizeListTitles            = false

timeZone                       = "US/Mountain"
languageCode                   = "en-us"
defaultContentLanguage         = "en"
defaultContentLanguageInSubdir = false

[outputs]
  home                         = ["html", "json"]
  section                      = ["html"]

[minify]
  minifyOutput = true

[imaging]
  resampleFilter = 'Lanczos'

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

[pagination]
  # set a small number to demo pagination
  pagerSize = 6

[taxonomies]
  tag        = "tags"
  category   = "categories"
  #series     = "series"

# --------------------------------
# i18n & Language-Specific Theme Settings
# --------------------------------

[languages]
  [languages.en]
    disabled          = false
    languageCode      = "en-us"
    languageDirection = "ltr"
    languageName      = "English"
    hasCJKLanguage    = false
    title             = "S.K. Puindo"
    weight            = 1

# --------------------------------
# Site Navigation
# --------------------------------

[languages.en.menus]
  [[languages.en.menus.main]]
    identifier = "books"
    name       = "Books"
    pageRef    = "/books"
    weight     = 5
  [[languages.en.menus.main]]
    identifier = "posts"
    name       = "Posts"
    pageRef    = "/posts"
    weight     = 10
  [[languages.en.menus.main]]
    identifier = "tags"
    name       = "Tags"
    pageRef    = "/tags"
    weight     = 20
#  [[languages.en.menus.main]]
#    identifier = "series"
#    name       = "Series"
#    pageRef    = "/series"
#    weight     = 30
  [[languages.en.menus.main]]
    identifier = "archives"
    name       = "Archives"
    pageRef    = "/archives"
    weight     = 40
  [[languages.en.menus.main]]
    identifier = "search"
    name       = "Search"
    pageRef    = "/search"
    weight     = 50

# --------------------------------
# Markdown Rendering
# --------------------------------

#[markup]
#  [markup.goldmark]
#    [markup.goldmark.parser]
#      # 必要：不要把 <img> 包在 <p> 裡面 (以便透過 `{width="100" ...}` 設定屬性)
#      # https://gohugo.io/content-management/markdown-attributes/#standalone-images
#      wrapStandAloneImageWithinParagraph = false
#      [markup.goldmark.parser.attribute]
#      # 允許使用 `{class="foo bar" id="baz"}` 或 `{.foo .bar #baz}` 語法，為 Markdown 元素增加 HTML 元素屬性 (不限 class / ID)
#      # https://gohugo.io/content-management/markdown-attributes/
#        # 允許區塊元素使用
#        block                    = true
#        # 支援標題元素使用
#        title                    = true
#    [markup.goldmark.renderer]
#      unsafe                     = true
#  [markup.highlight]
#    # 必要：讓程式碼區塊使用 CSS class，以便語法上色
#    # https://gohugo.io/configuration/markup/#highlight
#    noClasses                    = false
#  [markup.tableOfContents]
#  # 目次樣式設定
#  # https://gohugo.io/configuration/markup/#table-of-contents
#    startLevel = 2
#    endLevel = 3


# ================================
# Theme Settings
# ================================

[params]
  [params.neso]
    #time_format                        = "2006 January 02"
    time_format                        = "2006.01.02"
    show_breadcrumbs                   = true
    ext_link_indicator                 = true
    ext_link_no_opener_referrer        = true
    ext_link_new_window                = true
    [params.neso.branding]
      logo_text                        = "S.K. Puindo"
      hide_logo_text                   = false
      logo_image                       = "img/logo.svg"
      logo_image_dark                  = "img/logo_dark.svg"
      og_image                         = "img/metadata/ogimg.png"
      favicon_ico                      = "favicon.ico"
      favicon_svg                      = "img/metadata/favicon.svg"
      apple_touch_icon                 = "img/metadata/apple-touch-icon.png"
      pwa_short_title                  = "S.K. Puindo"
      pwa_theme_color_light            = "#f5f6f7"
      pwa_theme_color_dark             = "#000000"
      pwa_icon_svg                     = "img/metadata/pwa-icon.svg"
      pwa_icon_192                     = "img/metadata/pwa-icon-192.png"
      pwa_icon_512                     = "img/metadata/pwa-icon-512.png"
      pwa_icon_maskable_svg            = "img/metadata/pwa-icon-maskable.svg"
      pwa_icon_maskable_192            = "img/metadata/pwa-icon-maskable-192.png"
      pwa_icon_maskable_512            = "img/metadata/pwa-icon-maskable-512.png"
    [params.neso.social]
      [[params.neso.social.links]]
        name                           = "BlueSky"
        url                            = "https://bsky.app/profile/skpuindo.com"
      [[params.neso.social.links]]
        name                           = "Mastodon"
        url                            = "https://mastodon.sdf.org/@skpuindo"
    [params.neso.home]
      display_mode                     = "profile"
      [params.neso.home.list]
        featured_entries_limit         = 2
      [params.neso.home.profile]
        avatar_image                   = "img/jessdunnthis_spider.png"
        avatar_image_alt_text          = "S.K. Puindo's profile photo"
        [[params.neso.home.profile.link_btns]]
          label                        = "Posts"
          url                          = "posts/"
        [[params.neso.home.profile.link_btns]]
          label                        = "Books"
          url                          = "books/"
    [params.neso.list]
      prominent_first_entry            = true
      disable_responsive_cover_image   = false
      hide_summary                     = false
    [params.neso.page]
      ext_link_indicator               = true
      ext_link_no_opener_referrer      = true
      ext_link_new_window              = true
      show_breadcrumbs                 = true
      show_prev_next                   = true
      show_share                       = true
      share_providers                  = ["bluesky", "reddit", "x", "facebook", "linkedin", "reddit"]
    [params.neso.seo]
      site_description                 = "Dark epic fantasy author"
      site_keywords                    = ["epic fantasy", "dark epic fantasy", "writing", "story structure", "outlining", "S. K. Puindo"]
      site_author                      = ["S.K. Puindo"]

    [params.neso.search]
      input_placeholder                = "Title, keywords..."
